---
title: "dse trial"
author: "jiya"
date: "2024-01-24"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wk2_stocks <- readRDS("~/DSE3101/wk2_stocks.rds")
str(wk2_stocks)
```

### stats on returns 

```{r}
sum(wk2_stocks$SPY_returns)*100
```
The cumulative returns of the S&P index during this period is `r round(sum(wk2_stocks$SPY_returns)*100; 2)`%.
```{r}
mean(wk2_stocks$SPY_returns)*100
```
The average daily returns of the S&P index during this period is `r round(mean(wk2_stocks$SPY_returns)*100; 2)`%.
```{r}
sd(wk2_stocks$SPY_returns)*100
```
The average daily returns of the S&P index during this period is `r round(sd(wk2_stocks$SPY_returns)*100; 2)`%.

### S&P prices
```{r}
install.packages("tidyverse")
library(tidyverse)
ggplot(data = wk2_stocks, aes(x = wk2_stocks, y = wk2_stocks$SPY_prices)) +
  geom_line()
```
### S&P Yearly returns
```{r}
wk2_stocks %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarise(yr_return = sum(SPY_returns)*100)
ggplot(aes(x = year, y = yr_return)) +
  geom_col()
```